/* Automatic generated by './build/bin/build-entry.js' */

import SinoPage from '../packages/sinoPage/index.js';
import SinoDialog from '../packages/sinoDialog/index.js';
import SinoDropdown from '../packages/sinoDropdown/index.js';
import SinoDropdownMenu from '../packages/sinoDropdownMenu/index.js';
import SinoDropdownItem from '../packages/sinoDropdownItem/index.js';
import SinoMenu from '../packages/sinoMenu/index.js';
import SinoMenuItem from '../packages/sinoMenuItem/index.js';
import SinoMenuItemGroup from '../packages/sinoMenuItemGroup/index.js';
import SinoSubmenu from '../packages/sinoSubmenu/index.js';
import SinoAutocomplete from '../packages/sinoAutocomplete/index.js';
import SinoInput from '../packages/sinoInput/index.js';
import SinoInputNumber from '../packages/sinoInputNumber/index.js';
import SinoRadio from '../packages/sinoRadio/index.js';
import SinoRadioGroup from '../packages/sinoRadioGroup/index.js';
import SinoCheckbox from '../packages/sinoCheckbox/index.js';
import SinoCheckboxGroup from '../packages/sinoCheckboxGroup/index.js';
import SinoSwitch from '../packages/sinoSwitch/index.js';
import SinoSelect from '../packages/sinoSelect/index.js';
import SinoOption from '../packages/sinoOption/index.js';
import SinoOptions from '../packages/sinoOptions/index.js';
import SinoCreateSelect from '../packages/sinoCreateSelect/index.js';
import SinoCreateOption from '../packages/sinoCreateOption/index.js';
import SinoCreateOptionGroup from '../packages/sinoCreateOptionGroup/index.js';
import SinoButton from '../packages/sinoButton/index.js';
import SinoTable from '../packages/sinoTable/index.js';
import SinoTableColumn from '../packages/sinoTableColumn/index.js';
import SinoAutoTable from '../packages/sinoAutoTable/index.js';
import SinoAutoTableColumn from '../packages/sinoAutoTableColumn/index.js';
import SinoDatePicker from '../packages/sinoDatePicker/index.js';
import SinoTimeSelect from '../packages/sinoTimeSelect/index.js';
import SinoTimePicker from '../packages/sinoTimePicker/index.js';
import SinoPopover from '../packages/sinoPopover/index.js';
import SinoTooltip from '../packages/sinoTooltip/index.js';
import Tooltip from '../packages/tooltip/index.js';
import SinoTitle from '../packages/sinoTitle/index.js';
import MessageBox from '../packages/message-box/index.js';
import SinoBreadcrumb from '../packages/sinoBreadcrumb/index.js';
import SinoBreadcrumbItem from '../packages/sinoBreadcrumbItem/index.js';
import SinoForm from '../packages/sinoForm/index.js';
import SinoFormItem from '../packages/sinoFormItem/index.js';
import SinoTabs from '../packages/sinoTabs/index.js';
import SinoTabPane from '../packages/sinoTabPane/index.js';
import Tag from '../packages/tag/index.js';
import SinoTree from '../packages/sinoTree/index.js';
import SinoTreeNode from '../packages/sinoTreeNode/index.js';
import Notification from '../packages/notification/index.js';
import Loading from '../packages/loading/index.js';
import Icon from '../packages/icon/index.js';
import Row from '../packages/row/index.js';
import SinoUpload from '../packages/sinoUpload/index.js';
import SinoProgress from '../packages/sinoProgress/index.js';
import Spinner from '../packages/spinner/index.js';
import Message from '../packages/message/index.js';
import SinoBadge from '../packages/sinoBadge/index.js';
import Rate from '../packages/rate/index.js';
import SinoSteps from '../packages/sinoSteps/index.js';
import SinoStep from '../packages/sinoStep/index.js';
import SinoScrollbar from '../packages/sinoScrollbar/index.js';
import SinoRebound from '../packages/sinoRebound/index.js';
import Transfer from '../packages/transfer/index.js';
import SinoLinkContainer from '../packages/sinoLinkContainer/index.js';
import SinoCon from '../packages/sinoCon/index.js';
import SinoIconSelect from '../packages/sinoIconSelect/index.js';
import SinoIconOption from '../packages/sinoIconOption/index.js';
import SinoIconOptions from '../packages/sinoIconOptions/index.js';
import SinoCascader from '../packages/sinoCascader/index.js';
import SinoImg from '../packages/sinoImg/index.js';
import locale from 'sinoUI/src/locale';
import CollapseTransition from 'sinoUI/src/transitions/collapse-transition';

const components = [
  SinoPage,
  SinoDialog,
  SinoDropdown,
  SinoDropdownMenu,
  SinoDropdownItem,
  SinoMenu,
  SinoMenuItem,
  SinoMenuItemGroup,
  SinoSubmenu,
  SinoAutocomplete,
  SinoInput,
  SinoInputNumber,
  SinoRadio,
  SinoRadioGroup,
  SinoCheckbox,
  SinoCheckboxGroup,
  SinoSwitch,
  SinoSelect,
  SinoOption,
  SinoOptions,
  SinoCreateSelect,
  SinoCreateOption,
  SinoCreateOptionGroup,
  SinoButton,
  SinoTable,
  SinoTableColumn,
  SinoAutoTable,
  SinoAutoTableColumn,
  SinoDatePicker,
  SinoTimeSelect,
  SinoTimePicker,
  SinoPopover,
  SinoTooltip,
  Tooltip,
  SinoTitle,
  SinoBreadcrumb,
  SinoBreadcrumbItem,
  SinoForm,
  SinoFormItem,
  SinoTabs,
  SinoTabPane,
  Tag,
  SinoTree,
  SinoTreeNode,
  Icon,
  Row,
  SinoUpload,
  SinoProgress,
  Spinner,
  SinoBadge,
  Rate,
  SinoSteps,
  SinoStep,
  SinoScrollbar,
  SinoRebound,
  Transfer,
  SinoLinkContainer,
  SinoCon,
  SinoIconSelect,
  SinoIconOption,
  SinoIconOptions,
  SinoCascader,
  SinoImg,
  CollapseTransition
];

const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return;
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.map(component => {
    Vue.component(component.name, component);
  });

  Vue.use(Loading.directive);

  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$msgbox = MessageBox;
  Vue.prototype.$alert = MessageBox.alert;
  Vue.prototype.$confirm = MessageBox.confirm;
  Vue.prototype.$prompt = MessageBox.prompt;
  Vue.prototype.$notify = Notification;
  Vue.prototype.$message = Message;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
};

module.exports = {
  version: '0.0.17-test',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Loading,
  SinoPage,
  SinoDialog,
  SinoDropdown,
  SinoDropdownMenu,
  SinoDropdownItem,
  SinoMenu,
  SinoMenuItem,
  SinoMenuItemGroup,
  SinoSubmenu,
  SinoAutocomplete,
  SinoInput,
  SinoInputNumber,
  SinoRadio,
  SinoRadioGroup,
  SinoCheckbox,
  SinoCheckboxGroup,
  SinoSwitch,
  SinoSelect,
  SinoOption,
  SinoOptions,
  SinoCreateSelect,
  SinoCreateOption,
  SinoCreateOptionGroup,
  SinoButton,
  SinoTable,
  SinoTableColumn,
  SinoAutoTable,
  SinoAutoTableColumn,
  SinoDatePicker,
  SinoTimeSelect,
  SinoTimePicker,
  SinoPopover,
  SinoTooltip,
  Tooltip,
  SinoTitle,
  MessageBox,
  SinoBreadcrumb,
  SinoBreadcrumbItem,
  SinoForm,
  SinoFormItem,
  SinoTabs,
  SinoTabPane,
  Tag,
  SinoTree,
  SinoTreeNode,
  Notification,
  Icon,
  Row,
  SinoUpload,
  SinoProgress,
  Spinner,
  Message,
  SinoBadge,
  Rate,
  SinoSteps,
  SinoStep,
  SinoScrollbar,
  SinoRebound,
  Transfer,
  SinoLinkContainer,
  SinoCon,
  SinoIconSelect,
  SinoIconOption,
  SinoIconOptions,
  SinoCascader,
  SinoImg
};
